---
- name: download app from github and deploy it to tomcat6
  get_url: >
    url={{ app_url }}}
    dest={{ catalina_home }}/webapps/ 
    validate_certs=no

- name: chown app war
  file: >
    path={{ catalina_home }}/webapps/ROOT.war
    owner=tomcat
    group=tomcat
  notify:
  - restart tomcat

- name: download posgresql connector
  get_url: >
    url={{ jdbc_driver_url }} 
    dest={{ catalina_home }}/lib
  notify:
  - restart tomcat

- name: add postgre resource to context.xml
  lineinfile: >
    dest={{ catalina_home }}/conf/context.xml
    line='<Resource name="jdbc/postgres" auth="Container" type="javax.sql.DataSource" driverClassName="org.postgresql.Driver" url="jdbc:postgresql://127.0.0.1:5432/app_test" user="tomcat" password="postgres" maxActive="20" maxIdle="10" maxWait="-1"/>'
    state=present
    insertbefore="^</Context>"
  notify:
  - restart tomcat