---
- name: create virtual host for tomcat
  template: src=vhost-tomcat.conf dest=/etc/httpd/conf.d/vhost-tomcat.conf
  notify:
  - restart apache

- name: create virtual host DocumentRoot {{ document_root }}
  file: path={{ document_root }} owner=apache group=apache state=directory recurse=yes

- name: copy maintenance.html page to virtual host DocumentRoot {{ document_root }}
  copy: src=maintenance.html dest={{ document_root }}/maintenance.html owner=apache group=apache