---
- name: change postgre authentication
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf
  register: config
  notify:
  - restart postgresql

- name: reload postrge configuration
  service: name=postgresql state=restarted
  when: config|changed

- name: create database {{ db_name }}
  postgresql_db: name={{ db_name }} state=present
  register: database

- name: create user tomcat
  postgresql_user: name={{ db_user }} db={{ db_name }} state=present

- name: grant privileges to user {{ db_user }} on {{ db_name }} db
  postgresql_privs: >
    privs=ALL 
    db={{ db_name }} 
    state=present 
    role={{ db_user }} 
    objs=ALL_IN_SCHEMA

- name: copy postgres dump
  copy: >
    src=app_test.sql
    dest=/tmp/app_test.sql
    owner=tomcat
    group=tomcat

- name: restore db from dump
  command: psql -U {{ db_user }} -d {{ db_name }} -f /tmp/app_test.sql
  when: database|changed