---
- name: install tomcat6 and httpd
  yum: name={{item}} state=latest
  with_items:
    - tomcat6
    - httpd

- name: ensure tomcat6 service is started
  service: name=tomcat6 state=started

- name: enable tomcat6 service to start at boot
  service: name=tomcat6 enabled=yes

- name: install postgresql-server
  yum: name=postgresql-server state=latest
  register: result

- name: initialize postgresql
  command: service postgresql initdb
  when: result|changed

- name: ensure postgresql service is started
  service: name=postgresql state=started

- name: enable postgresql service to start at boot
  service: name=postgresql enabled=yes

- name: download app from github and deploy it to tomcat6
  get_url: url=https://github.com/rightscale/examples/blob/unified_tomcat_pg/ROOT.war?raw=true dest=/usr/share/tomcat6/webapps/ mode=0440 validate_certs=no

- name: chown app
  file: path=/usr/share/tomcat6/webapps/ROOT.war owner=tomcat group=tomcat

