---
- name: install tomcat6, httpd and some other dependencies
  yum: name={{item}} state=latest
  with_items:
    - tomcat6
    - httpd
    - libselinux-python
    - python-psycopg2
    - postgresql

- name: install postgresql-server
  yum: name=postgresql-server state=latest
  register: result

- name: initialize postgresql
  command: service postgresql initdb
  when: result|changed

- name: enable services to start at boot
  service: name={{item}} enabled=yes
  with_items:
  - tomcat6
  - httpd
  - postgresql

- name: start services
  service: name={{item}} state=started
  with_items:
  - tomcat6
  - httpd
  - postgresql